# Generated by Django 2.1.2 on 2018-11-29 11:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articoloblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(blank=True, default='', max_length=300)),
                ('sottotitolo', models.TextField(blank=True, default='', null=True)),
                ('testo', models.TextField(blank=True, default='', null=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Articolo',
                'verbose_name_plural': 'Articoli',
            },
        ),
        migrations.CreateModel(
            name='Categoriablog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Testatablog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(blank=True, default='', max_length=300)),
                ('testo', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'Testata',
                'verbose_name_plural': 'Testata',
            },
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Immagine', 'verbose_name_plural': 'Immagini'},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='immagine',
        ),
        migrations.AddField(
            model_name='testatablog',
            name='immagine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Foto', to='blog.Image'),
        ),
        migrations.AddField(
            model_name='articoloblog',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Typeart', to='blog.Image'),
        ),
        migrations.AddField(
            model_name='articoloblog',
            name='immagine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fotoblog', to='blog.Image'),
        ),
    ]
