# Generated by Django 2.1.2 on 2018-11-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/media/img/')),
                ('label1', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
