# Generated by Django 2.1.2 on 2018-11-28 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(blank=True, default='', max_length=300)),
                ('testo', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/img/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='immagine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Foto', to='blog.Image'),
        ),
    ]
