# Generated by Django 2.1.2 on 2018-11-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181128_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articoloblog',
            options={'verbose_name_plural': 'Articoli'},
        ),
        migrations.AlterModelOptions(
            name='testatablog',
            options={'verbose_name_plural': 'Testata'},
        ),
        migrations.AddField(
            model_name='articoloblog',
            name='sottotitolo',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
