# Generated by Django 2.1.2 on 2018-11-28 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181128_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='articoloblog',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
