# Generated by Django 2.1.2 on 2018-11-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181128_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriablog',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorie'},
        ),
    ]
