# Generated by Django 2.1.2 on 2018-11-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/home/media/'),
        ),
    ]
