# Generated by Django 2.1.2 on 2018-11-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181118_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label1', models.CharField(max_length=100)),
                ('label2', models.CharField(max_length=100)),
            ],
        ),
    ]
