# Generated by Django 2.1.2 on 2018-11-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20181118_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presentazione',
            old_name='video',
            new_name='videolink',
        ),
        migrations.AddField(
            model_name='presentazione',
            name='videodescrizione',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
