# Generated by Django 2.1.2 on 2018-11-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_presentazionepunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/'),
        ),
    ]
