# Generated by Django 2.1.2 on 2018-11-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_staffdes_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/media/')),
                ('label1', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('label2', models.CharField(blank=True, default='', max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blogdes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label1', models.CharField(max_length=100)),
                ('label2', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/media/')),
            ],
        ),
    ]
