# Generated by Django 2.1.2 on 2018-11-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_blog_blogdes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='link',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
