# Generated by Django 2.1.2 on 2018-11-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_blog_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footeradv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label1', models.CharField(max_length=100)),
                ('label2', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/media/')),
            ],
        ),
    ]
