# Generated by Django 2.1.2 on 2018-11-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_footeradv'),
    ]

    operations = [
        migrations.AddField(
            model_name='titolo',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='titolo',
            name='indirizzo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='titolo',
            name='linkfacebook',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='titolo',
            name='linkinstagram',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='titolo',
            name='linktwitter',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='titolo',
            name='telefono',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogdes',
            name='label1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogdes',
            name='label2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='footeradv',
            name='label1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='footeradv',
            name='label2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffdes',
            name='label1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffdes',
            name='label2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='testata',
            name='label1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='testata',
            name='label2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='testata',
            name='label3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='testata',
            name='label4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='titolo',
            name='label1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='titolo',
            name='label2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
