# Generated by Django 2.1.2 on 2018-11-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20181122_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='servizi',
            name='testo1a',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='servizi',
            name='testo21',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='servizi',
            name='testo31',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='servizi',
            name='testo1',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='servizi',
            name='testo2',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='servizi',
            name='testo3',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
