# Generated by Django 2.1.2 on 2018-11-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20181122_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servizides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label1', models.CharField(blank=True, default='', max_length=100)),
                ('label2', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='servizi',
            name='image',
        ),
    ]
