# Generated by Django 2.1.2 on 2018-11-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20181122_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servizi',
            name='label2',
        ),
        migrations.RemoveField(
            model_name='servizi',
            name='label3',
        ),
        migrations.RemoveField(
            model_name='servizi',
            name='testo1a',
        ),
        migrations.RemoveField(
            model_name='servizi',
            name='testo21',
        ),
        migrations.RemoveField(
            model_name='servizi',
            name='testo31',
        ),
        migrations.AddField(
            model_name='servizi',
            name='flaticon_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='servizi',
            name='testo4',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='servizi',
            name='testo5',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
