# Generated by Django 2.1.2 on 2018-11-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20181122_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentazione',
            name='label1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
