# Generated by Django 2.1.2 on 2018-11-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_contatto'),
    ]

    operations = [
        migrations.AddField(
            model_name='titolo',
            name='sitoweb',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
