# Generated by Django 2.1.2 on 2018-11-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_titolo_sitoweb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contattorichiesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('soggetto', models.CharField(blank=True, default='', max_length=200)),
                ('oggetto', models.TextField(blank=True, default='')),
                ('data', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
