# Generated by Django 2.1.2 on 2018-11-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_contattorichiesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contattorichiesta',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
