# Generated by Django 2.1.2 on 2018-11-27 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20181127_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contattorichiesta',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 27, 13, 20, 19, 97230)),
        ),
    ]
