# Generated by Django 2.1.2 on 2018-11-27 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20181127_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contattorichiesta',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
