# Generated by Django 2.1.2 on 2018-11-27 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20181127_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contattorichiesta',
            name='data',
        ),
        migrations.AddField(
            model_name='contattorichiesta',
            name='datarichiesta',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 27, 13, 35, 56, 355486, tzinfo=utc)),
        ),
    ]
