# Generated by Django 2.1.2 on 2018-11-27 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20181127_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contattorichiesta',
            name='datarichiesta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
